---
title: "Riley File"
author: "Riley Maher"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing Packages

```{r}
library(ggplot2)
library(dplyr)
library(scales)
```

# Loading Data

```{r}
hotels <- read.csv('hotel_bookings.csv', stringsAsFactors = TRUE)
head(hotels)
```

```{r}
str(hotels)
```

```{r}
summary(hotels)
```

# Initial Data Analysis

```{r}
# Calculating the rate of canceled bookings
cancellation_rate <- label_percent()(round(sum(hotels$is_canceled)/nrow(hotels), 2))
cancellation_rate
```
Of all the bookings across all hotels, `r cancellation_rate` of them were canceled.

```{r}
#Finding and graphing the number of arrivals by month
month_arrivals <- data.frame(sort(table(hotels$arrival_date_month)))

ggplot(data = month_arrivals, aes(x = Var1,y = Freq)) +
  geom_bar(stat = "identity")
```

```{r}
#Finding and graphing the number of arrivals by year
year_arrivals <- data.frame(sort(table(hotels$arrival_date_year)))

ggplot(data = year_arrivals, aes(x = Var1,y = Freq)) +
  geom_bar(stat = "identity")
```

```{r}
# Calculating the top 10 countries with hotels
country_hotels <- data.frame(sort(table(hotels$country), decreasing = TRUE))[1:10,]

ggplot(data = country_hotels, aes(x = Var1,y = Freq)) +
  geom_bar(stat = "identity")
```

```{r}
# Finding the types of hotels
hotel_types <- data.frame(table(hotels$hotel))
hotel_types

# Creating a pie chart of hotel types
ggplot(hotel_types, aes(x="", y=Freq, fill=Var1)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar('y')
```

# Advanced Data Analysis

```{r}
# Calculating the aveage daily rate of bookings that did/didn't use an agent
mean_adr_agent <- hotels %>%
  filter(agent != 'NULL') %>%
  summarize(mean_adr_agent = mean(adr, na.rm = TRUE))

mean_adr_no_agent <- hotels %>%
  filter(agent == 'NULL') %>%
  summarize(mean_adr_no_agent = mean(adr, na.rm = TRUE))

mean_adr_agent
mean_adr_no_agent
```

```{r}
# Seeing the type of meals families with kids buy
kids <- hotels %>%
  filter(children > 1)

meals_with_kids <- data.frame(table(kids$meal))

meals_with_kids %>%
  mutate(meal_percent = Freq / nrow(kids))

# Seeing the type of meals families with no kids buy
no_kids <- hotels %>%
  filter(children == 0)

meals_with_no_kids <- data.frame(table(no_kids$meal))

meals_with_no_kids %>%
  mutate(meal_percent = Freq / nrow(no_kids))
```

